### PR TITLE
Create Dockerfile

### PR DESCRIPTION
**Pull request by balk77**
Dockerfile for https://hub.docker.com/r/balk77/nefit-easy-http-server/

### CODE REVIEW

**Comment by robertklep** [comment]
Great!

Just a question though: it seems to me that it can be shortened to this:
```
FROM node:11

RUN npm install nefit-easy-http-server -g

ENV NEFIT_IP="127.0.0.1"
ENV NEFIT_PORT=3000

CMD easy-server --host=$NEFIT_IP --port=$NEFIT_PORT
```

There's no real need to copy the source to the image, or run `npm install`.

**Comment by balk77** [comment]
yes, tried it and it works. We can even use 
```
FROM node:alpine

RUN npm install nefit-easy-http-server -g

ENV NEFIT_IP="127.0.0.1"
ENV NEFIT_PORT=3000

CMD easy-server --host=$NEFIT_IP --port=$NEFIT_PORT

```
as it will reduce the image by a factor 10

**Comment by robertklep** [comment]
Not sure which version of Node that will use, you can also use `FROM node:10.13.0-alpine` to pin it to the current LTS version.

**Comment by balk77** [comment]
agreed, I have no preference

**Comment by robertklep** [comment]
Dockerfile added in `e4cbbba`, thanks again!

**Pull request closed without merging**
